import { Country } from './src/country';
import * as data from './data.json';

export const testCountries: Country[] = [
  // Africa
  {
    name: {
      common: "Algeria",
      official: "People's Democratic Republic of Algeria",
      nativeName: {}
    },
    tld: [".dz"],
    cca2: "DZ",
    ccn3: "012",
    cca3: "DZA",
    independent: true,
    status: "officially-assigned",
    subregion: "Northern Africa",
    borders: ["TUN", "LBY", "NER", "ESH", "MRT", "MLI", "MAR"],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Algiers"],
    altSpellings: ["DZ", "Dzayer", "Algérie"],
    region: "Africa",
    languages: {},
    translations: {},
    latlng: [28, 3],
    landlocked: false,
    area: 2381741,
    demonyms: {},
    flag: "https://flagcdn.com/dz.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 44700000,
    car: { signs: [""], side: "left" },
    timezones: ["UTC+01:00"],
    continents: ["Africa"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  {
    name: {
      common: "Angola",
      official: "Republic of Angola",
      nativeName: {}
    },
    tld: [".ao"],
    cca2: "AO",
    ccn3: "024",
    cca3: "AGO",
    independent: true,
    status: "officially-assigned",
    subregion: "Middle Africa",
    borders: ["COG", "COD", "ZMB", "NAM"],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Luanda"],
    altSpellings: ["AO", "República de Angola", "ʁɛpublika de an'ɡɔla"],
    region: "Africa",
    languages: {},
    translations: {},
    latlng: [-12.5, 18.5],
    landlocked: false,
    area: 1246700,
    demonyms: {},
    flag: "https://flagcdn.com/ao.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 32866268,
    car: { signs: [""], side: "left" },
    timezones: ["UTC+01:00"],
    continents: ["Africa"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  // Americas
  {
    name: {
      common: "Argentina",
      official: "Argentine Republic",
      nativeName: {}
    },
    tld: [".ar"],
    cca2: "AR",
    ccn3: "032",
    cca3: "ARG",
    independent: true,
    status: "officially-assigned",
    subregion: "South America",
    borders: ["BOL", "BRA", "CHL", "PRY", "URY"],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Buenos Aires"],
    altSpellings: ["AR", "Argentine Republic", "República Argentina"],
    region: "Americas",
    languages: {},
    translations: {},
    latlng: [-34, -64],
    landlocked: false,
    area: 2780400,
    demonyms: {},
    flag: "https://flagcdn.com/ar.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 45376763,
    car: { signs: [""], side: "left" },
    timezones: ["UTC-03:00"],
    continents: ["Americas"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  {
    name: {
      common: "Bahamas",
      official: "Commonwealth of the Bahamas",
      nativeName: {}
    },
    tld: [".bs"],
    cca2: "BS",
    ccn3: "044",
    cca3: "BHS",
    independent: true,
    status: "officially-assigned",
    subregion: "Caribbean",
    borders: [],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Nassau"],
    altSpellings: ["BS", "Commonwealth of the Bahamas"],
    region: "Americas",
    languages: {},
    translations: {},
    latlng: [24.25, -76],
    landlocked: false,
    area: 13943,
    demonyms: {},
    flag: "https://flagcdn.com/bs.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 393248,
    car: { signs: [""], side: "left" },
    timezones: ["UTC-05:00"],
    continents: ["Americas"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  // Asia
  {
    name: {
      common: "Afghanistan",
      official: "Islamic Republic of Afghanistan",
      nativeName: {}
    },
    tld: [".af"],
    cca2: "AF",
    ccn3: "004",
    cca3: "AFG",
    independent: true,
    status: "officially-assigned",
    subregion: "Southern Asia",
    borders: ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Kabul"],
    altSpellings: ["AF", "Afġānistān"],
    region: "Asia",
    languages: {},
    translations: {},
    latlng: [33, 65],
    landlocked: false,
    area: 652230,
    demonyms: {},
    flag: "https://flagcdn.com/af.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 40218234,
    car: { signs: [""], side: "left" },
    timezones: ["UTC+04:30"],
    continents: ["Asia"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  {
    name: {
      common: "Armenia",
      official: "Republic of Armenia",
      nativeName: {}
    },
    tld: [".am"],
    cca2: "AM",
    ccn3: "051",
    cca3: "ARM",
    independent: true,
    status: "officially-assigned",
    subregion: "Western Asia",
    borders: ["AZE", "GEO", "IRN", "TUR"],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Yerevan"],
    altSpellings: ["Հայաստանի Հանրապետություն"],
    region: "Asia",
    languages: {},
    translations: {},
    latlng: [40, 45],
    landlocked: false,
    area: 29743,
    demonyms: {},
    flag: "https://flagcdn.com/am.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 2963234,
    car: { signs: [""], side: "left" },
    timezones: ["UTC+04:00"],
    continents: ["Asia"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  // Europe
  {
    name: {
      common: "Albania",
      official: "Republic of Albania",
      nativeName: {}
    },
    tld: [".al"],
    cca2: "AL",
    ccn3: "008",
    cca3: "ALB",
    independent: true,
    status: "officially-assigned",
    subregion: "Southern Europe",
    borders: ["MNE", "GRC", "MKD", "UNK"],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Tirana"],
    altSpellings: ["AL", "Shqipëri", "Shqipëria", "Shqipnia"],
    region: "Europe",
    languages: {},
    translations: {},
    latlng: [41, 20],
    landlocked: false,
    area: 28748,
    demonyms: {},
    flag: "https://flagcdn.com/al.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 2837743,
    car: { signs: [""], side: "left" },
    timezones: ["UTC+01:00"],
    continents: ["Europe"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  {
    name: {
      common: "Austria",
      official: "Republic of Austria",
      nativeName: {}
    },
    tld: [".at"],
    cca2: "AT",
    ccn3: "040",
    cca3: "AUT",
    independent: true,
    status: "officially-assigned",
    subregion: "Central Europe",
    borders: ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Vienna"],
    altSpellings: ["AT", "Österreich", "Osterreich", "Oesterreich"],
    region: "Europe",
    languages: {},
    translations: {},
    latlng: [47.33333333, 13.33333333],
    landlocked: false,
    area: 83871,
    demonyms: {},
    flag: "https://flagcdn.com/at.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 8917205,
    car: { signs: [""], side: "left" },
    timezones: ["UTC+01:00"],
    continents: ["Europe"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  // Oceania
  {
    name: {
      common: "Australia",
      official: "Commonwealth of Australia",
      nativeName: {}
    },
    tld: [".au"],
    cca2: "AU",
    ccn3: "036",
    cca3: "AUS",
    independent: true,
    status: "officially-assigned",
    subregion: "Australia and New Zealand",
    borders: [],
    unMember: true,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Canberra"],
    altSpellings: ["AU"],
    region: "Oceania",
    languages: {},
    translations: {},
    latlng: [-27, 133],
    landlocked: false,
    area: 7692024,
    demonyms: {},
    flag: "https://flagcdn.com/au.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 25687041,
    car: { signs: [""], side: "left" },
    timezones: ["UTC+11:30"],
    continents: ["Oceania"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
  {
    name: {
      common: "American Samoa",
      official: "American Samoa",
      nativeName: {}
    },
    tld: [".as"],
    cca2: "AS",
    ccn3: "016",
    cca3: "ASM",
    independent: false,
    status: "officially-assigned",
    subregion: "Polynesia",
    borders: [],
    unMember: false,
    currencies: {},
    idd: { root: "", suffixes: [""] },
    capital: ["Pago Pago"],
    altSpellings: ["AS", "Amerika Sāmoa", "Amelika Sāmoa", "Sāmoa Amelika"],
    region: "Oceania",
    languages: {},
    translations: {},
    latlng: [-14.33333333, -170],
    landlocked: false,
    area: 199,
    demonyms: {},
    flag: "https://flagcdn.com/as.svg",
    maps: { googleMaps: "", openStreetMaps: "" },
    population: 55197,
    car: { signs: [""], side: "left" },
    timezones: ["UTC-11:00"],
    continents: ["Oceania"],
    flags: { png: '', svg: '' },
    coatOfArms: {},
    startOfWeek: "monday",
    capitalInfo: { latlng: [0, 0] },
  },
];